package dns

import (
	"context"
	"fmt"
	"net"
	"os"
	"os/exec"
	"runtime"
	"strings"
	"time"

	"github.com/miekg/dns"
)

// ResolverStatus holds diagnostic information about OS DNS resolution.
type ResolverStatus struct {
	OS             string
	Domain         string
	ResolverConfig string
	ConfigExists   bool
	ResolvingLocal bool
	ResolvedIP     string
	Error          string
}

// GetResolverPath returns the system resolver file path for macOS.
func GetResolverPath(domain string) string {
	return fmt.Sprintf("/etc/resolver/%s", domain)
}

// GenerateMacResolverConfig creates configuration text for /etc/resolver/<domain>.
func GenerateMacResolverConfig(ip string, port int) string {
	if port == 53 {
		return fmt.Sprintf("# Generated by Breez\nnameserver %s\n", ip)
	}
	return fmt.Sprintf("# Generated by Breez\nnameserver %s\nport %d\n", ip, port)
}

// CheckStatus diagnoses if the OS is successfully resolving *.domain queries.
func CheckStatus(domain string, dnsAddr string) ResolverStatus {
	st := ResolverStatus{
		OS:     runtime.GOOS,
		Domain: domain,
	}

	if runtime.GOOS == "darwin" {
		path := GetResolverPath(domain)
		st.ResolverConfig = path
		if _, err := os.Stat(path); err == nil {
			st.ConfigExists = true
		}
	}

	// 1. Direct query against our local DNS server
	testHost := fmt.Sprintf("breez-healthcheck.%s.", domain)
	c := &dns.Client{Timeout: 1 * time.Second}
	m := &dns.Msg{}
	m.SetQuestion(testHost, dns.TypeA)

	in, _, err := c.Exchange(m, dnsAddr)
	if err == nil && in != nil && len(in.Answer) > 0 {
		if a, ok := in.Answer[0].(*dns.A); ok {
			st.ResolvingLocal = true
			st.ResolvedIP = a.A.String()
		}
	} else if err != nil {
		st.Error = fmt.Sprintf("Local DNS server query failed on %s: %v", dnsAddr, err)
	}

	return st
}

// InstallMacResolver requires sudo and writes to /etc/resolver/<domain>
func InstallMacResolver(domain string, port int) error {
	if runtime.GOOS != "darwin" {
		return fmt.Errorf("automatic resolver configuration is currently supported natively on macOS (/etc/resolver)")
	}

	config := GenerateMacResolverConfig("127.0.0.1", port)
	resolverDir := "/etc/resolver"

	cmd := exec.Command("sudo", "mkdir", "-p", resolverDir)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to create %s: %w", resolverDir, err)
	}

	filePath := GetResolverPath(domain)
	writeCmd := exec.Command("sudo", "tee", filePath)
	writeCmd.Stdin = strings.NewReader(config)
	writeCmd.Stdout = nil
	writeCmd.Stderr = os.Stderr
	if err := writeCmd.Run(); err != nil {
		return fmt.Errorf("failed to write %s: %w", filePath, err)
	}

	// Flush dscacheutil & killall mDNSResponder on macOS
	_ = exec.Command("sudo", "dscacheutil", "-flushcache").Run()
	_ = exec.Command("sudo", "killall", "-HUP", "mDNSResponder").Run()

	return nil
}

// UninstallMacResolver removes the /etc/resolver/<domain> file.
func UninstallMacResolver(domain string) error {
	if runtime.GOOS != "darwin" {
		return nil
	}
	filePath := GetResolverPath(domain)
	cmd := exec.Command("sudo", "rm", "-f", filePath)
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("failed to remove %s: %w", filePath, err)
	}
	_ = exec.Command("sudo", "dscacheutil", "-flushcache").Run()
	_ = exec.Command("sudo", "killall", "-HUP", "mDNSResponder").Run()
	return nil
}

// ResolveHostWithSystem attempts to resolve a hostname using the OS resolver.
func ResolveHostWithSystem(host string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	var r net.Resolver
	ips, err := r.LookupIP(ctx, "ip4", host)
	if err != nil {
		return "", err
	}
	if len(ips) == 0 {
		return "", fmt.Errorf("no IP records found")
	}
	return ips[0].String(), nil
}
